public class Tes3Data
{
    public string attribute1 { get; set; }
    public string attribute2 { get; set; }
    public object specialization { get; set; }
    public string minor1 { get; set; }
    public string major1 { get; set; }
    public string minor2 { get; set; }
    public string major2 { get; set; }
    public string minor3 { get; set; }
    public string major3 { get; set; }
    public string minor4 { get; set; }
    public string major4 { get; set; }
    public string minor5 { get; set; }
    public string major5 { get; set; }
    public string flags { get; set; }
    public string services { get; set; }
    public string[] favored_attributes { get; set; }
    public Tes3Requirement[] requirements { get; set; }
    public string[] favored_skills { get; set; }
    public Tes3SkillBonuses skill_bonuses { get; set; }
    public object strength { get; set; }
    public object intelligence { get; set; }
    public object willpower { get; set; }
    public object agility { get; set; }
    public object speed { get; set; }
    public object endurance { get; set; }
    public object personality { get; set; }
    public object luck { get; set; }
    public float[] height { get; set; }
    public object weight { get; set; }
    public int volume { get; set; }
    public int[] range { get; set; }
    public int governing_attribute { get; set; }
    public float[] actions { get; set; }
    public string school { get; set; }
    public float base_cost { get; set; }
    public int[] color { get; set; }
    public float size { get; set; }
    public float size_cap { get; set; }
    public string spell_type { get; set; }
    public int cost { get; set; }
    public int value { get; set; }
    public string weapon_type { get; set; }
    public int health { get; set; }
    public float reach { get; set; }
    public int enchantment { get; set; }
    public int chop_min { get; set; }
    public int chop_max { get; set; }
    public int slash_min { get; set; }
    public int slash_max { get; set; }
    public int thrust_min { get; set; }
    public int thrust_max { get; set; }
    public string creature_type { get; set; }
    public int level { get; set; }
    public int magicka { get; set; }
    public int fatigue { get; set; }
    public int soul { get; set; }
    public int combat { get; set; }
    public int magic { get; set; }
    public int steath { get; set; }
    public int[] attack1 { get; set; }
    public int[] attack2 { get; set; }
    public int[] attack3 { get; set; }
    public int gold { get; set; }
    public string part { get; set; }
    public int vampire { get; set; }
    public int female { get; set; }
    public string bodypart_type { get; set; }
    public int time { get; set; }
    public int radius { get; set; }
    public string enchant_type { get; set; }
    public int max_charge { get; set; }
    public int disposition { get; set; }
    public int reputation { get; set; }
    public int rank { get; set; }
    public Tes3Stats stats { get; set; }
    public string armor_type { get; set; }
    public int armor_rating { get; set; }
    public string clothing_type { get; set; }
    public int uses { get; set; }
    public float quality { get; set; }
    public string apparatus_type { get; set; }
    public string[] effects { get; set; }
    public string[] skills { get; set; }
    public string[] attributes { get; set; }
    public string book_type { get; set; }
    public string skill { get; set; }
    public int[] grid { get; set; }
    public int granularity { get; set; }
    public int point_count { get; set; }
    public string dialogue_type { get; set; }
    public int speaker_rank { get; set; }
    public string speaker_sex { get; set; }
    public int player_rank { get; set; }
}
